"use client";

import React, { useState, useEffect } from "react";
import { BookOpen, Search, Filter, Sprout, Wheat, Grape, Bug, Droplets, Sun, ChevronRight, Bookmark } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

// Fallback empty array, will be populated on client mount or via static import
import defaultEncyclopediaData from "../data/encyclopedia.json";

const categories = [
  { id: 'all', label: 'All', icon: <BookOpen size={16} /> },
  { id: 'grains', label: 'Grains', icon: <Wheat size={16} /> },
  { id: 'vegetables', label: 'Vegetables', icon: <Sprout size={16} /> },
  { id: 'fruits', label: 'Fruits', icon: <Grape size={16} /> },
];

interface LibraryViewProps {
  userCrops: string;
}

export function LibraryView({ userCrops }: LibraryViewProps) {
  const [activeCategory, setActiveCategory] = useState('all');
  const [searchQuery, setSearchQuery] = useState("");
  const [encyclopediaData, setEncyclopediaData] = useState<any[]>([]);

  useEffect(() => {
    // In a real app, this might fetch from an API endpoint, but here we just load the JSON generated by the extraction script.
    setEncyclopediaData(defaultEncyclopediaData);
  }, []);

  const filteredData = encyclopediaData
    .filter(item => {
      const matchesCategory = activeCategory === 'all' || item.category === activeCategory;
      const matchesSearch = item.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
                           item.symptoms.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesCategory && matchesSearch;
    })
    .sort((a, b) => {
      const aMatch = userCrops.toLowerCase().includes(a.category.slice(0, -1));
      const bMatch = userCrops.toLowerCase().includes(b.category.slice(0, -1));
      if (aMatch && !bMatch) return -1;
      if (!aMatch && bMatch) return 1;
      return 0;
    });

  return (
    <div className="flex flex-col h-full bg-transparent overflow-hidden">
      {/* Header Section */}
      <div className="p-6 bg-white/50 backdrop-blur-md border-b border-slate-200/50">
        <h2 className="text-2xl font-black text-slate-800 tracking-tight">Agri-Encyclopedia</h2>
        <p className="text-sm text-slate-500 font-medium mt-1">Verified guides for crop protection and health.</p>
        
        {/* Search */}
        <div className="mt-6 relative group">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-emerald-500 transition-colors" size={18} />
          <input 
            type="text" 
            placeholder="Search diseases, crops, or treatments..." 
            className="w-full bg-slate-100 border-none rounded-2xl pl-12 pr-4 py-4 text-sm font-medium focus:ring-2 focus:ring-emerald-500/20 transition-all outline-none"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
        </div>

        {/* Categories Scroller */}
        <div className="flex gap-2 mt-6 overflow-x-auto pb-2 scrollbar-hide">
          {categories.map((cat) => (
            <button
              key={cat.id}
              onClick={() => setActiveCategory(cat.id)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all whitespace-nowrap ${
                activeCategory === cat.id 
                  ? 'bg-slate-900 text-white shadow-lg' 
                  : 'bg-white text-slate-500 hover:bg-slate-100'
              }`}
            >
              {cat.icon}
              {cat.label}
            </button>
          ))}
        </div>
      </div>

      {/* Content Grid */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 pb-24">
        <AnimatePresence mode="popLayout">
          {filteredData.map((item) => (
            <motion.div 
              key={item.id}
              layout
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              className="bg-white p-5 rounded-[2.5rem] border border-slate-100 shadow-sm group hover:shadow-xl hover:border-emerald-100 transition-all cursor-pointer relative overflow-hidden"
            >
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className={`w-12 h-12 rounded-2xl flex items-center justify-center bg-${item.color}-50 text-${item.color}-600`}>
                    <Bug size={24} />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <h3 className="font-black text-slate-800 text-lg group-hover:text-emerald-700 transition-colors">{item.title}</h3>
                      {userCrops.toLowerCase().includes(item.category.slice(0, -1)) && (
                        <span className="flex items-center gap-1 bg-emerald-100 text-emerald-700 text-[9px] font-black uppercase tracking-tighter px-2 py-0.5 rounded-full">
                          <Sprout size={10} />
                          Recommended
                        </span>
                      )}
                    </div>
                    <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">{item.category}</span>
                  </div>
                </div>
                <button className="text-slate-300 hover:text-emerald-500 transition-colors">
                  <Bookmark size={20} />
                </button>
              </div>

              <div className="grid grid-cols-2 gap-3 mb-4">
                <div className="bg-slate-50 p-3 rounded-2xl">
                  <div className="flex items-center gap-1.5 text-[10px] font-black text-slate-400 uppercase tracking-tighter mb-1">
                    <Droplets size={12} className="text-blue-500" />
                    Symptoms
                  </div>
                  <p className="text-[12px] font-bold text-slate-700 leading-tight">{item.symptoms}</p>
                </div>
                <div className="bg-slate-50 p-3 rounded-2xl">
                  <div className="flex items-center gap-1.5 text-[10px] font-black text-slate-400 uppercase tracking-tighter mb-1">
                    <Sun size={12} className="text-amber-500" />
                    Treatment
                  </div>
                  <p className="text-[12px] font-bold text-slate-700 leading-tight">{item.treatment}</p>
                </div>
              </div>

              <div className="flex items-center justify-between pt-2 border-t border-slate-50">
                <div className="flex items-center gap-2">
                  <div className={`w-2 h-2 rounded-full ${item.severity === 'High' ? 'bg-rose-500 animate-pulse' : 'bg-amber-500'}`} />
                  <span className="text-[11px] font-black uppercase tracking-widest text-slate-500">Severity: {item.severity}</span>
                </div>
                <div className="flex items-center gap-1 text-emerald-600 font-black text-[11px] uppercase tracking-widest group-hover:translate-x-1 transition-transform">
                  Full Guide
                  <ChevronRight size={14} />
                </div>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {filteredData.length === 0 && (
          <div className="flex flex-col items-center justify-center py-20 text-center opacity-40">
            <Search size={48} className="text-slate-300 mb-4" />
            <p className="font-black text-slate-500 uppercase tracking-widest">No matching guides found</p>
          </div>
        )}
      </div>
    </div>
  );
}
